/**
 * dic-client
 * Move your app forward with the diabetesincontrol API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DicClient) {
      root.DicClient = {};
    }
    root.DicClient.Author = factory(root.DicClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Author model module.
   * @module model/Author
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Author</code>.
   * @alias module:model/Author
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>Author</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Author} obj Optional instance to populate.
   * @return {module:model/Author} The populated <code>Author</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('slug')) {
        obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('first_name')) {
        obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
      }
      if (data.hasOwnProperty('last_name')) {
        obj['last_name'] = ApiClient.convertToType(data['last_name'], 'Number');
      }
      if (data.hasOwnProperty('nickname')) {
        obj['nickname'] = ApiClient.convertToType(data['nickname'], 'Number');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'Number');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'Number');
      }
    }
    return obj;
  }

  /**
   * id
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * slug
   * @member {String} slug
   */
  exports.prototype['slug'] = undefined;
  /**
   * title
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * first_name
   * @member {String} first_name
   */
  exports.prototype['first_name'] = undefined;
  /**
   * last_name
   * @member {Number} last_name
   */
  exports.prototype['last_name'] = undefined;
  /**
   * nickname
   * @member {Number} nickname
   */
  exports.prototype['nickname'] = undefined;
  /**
   * url
   * @member {Number} url
   */
  exports.prototype['url'] = undefined;
  /**
   * description
   * @member {Number} description
   */
  exports.prototype['description'] = undefined;



  return exports;
}));


