/**
 * dic-client
 * Move your app forward with the diabetesincontrol API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/Feed'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Error'), require('../model/Feed'));
  } else {
    // Browser globals (root is window)
    if (!root.SomeClient) {
      root.SomeClient = {};
    }
    root.SomeClient.PostsApi = factory(root.SomeClient.ApiClient, root.SomeClient.Error, root.SomeClient.Feed);
  }
}(this, function(ApiClient, Error, Feed) {
  'use strict';

  /**
   * Posts service.
   * @module api/PostsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new PostsApi. 
   * @alias module:api/PostsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * List Posts
     * posts list 
     * @param {Number} json Scope under which the request is made; determines fields present in response.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Feed}
     */
    this.diabetesTherapiesGet = function(json) {
      var postBody = null;

      // verify the required parameter 'json' is set
      if (json == undefined || json == null) {
        throw "Missing the required parameter 'json' when calling diabetesTherapiesGet";
      }


      var pathParams = {
      };
      var queryParams = {
        'json': json
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Feed;

      return this.apiClient.callApi(
        '/diabetes-therapies', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }
  };

  return exports;
}));
