/**
 * DIC API
 * Move your app forward with the diabetesincontrol API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/Feed'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Error'), require('../model/Feed'));
  } else {
    // Browser globals (root is window)
    if (!root.DicApi) {
      root.DicApi = {};
    }
    root.DicApi.PostsApi = factory(root.DicApi.ApiClient, root.DicApi.Error, root.DicApi.Feed);
  }
}(this, function(ApiClient, Error, Feed) {
  'use strict';

  /**
   * Posts service.
   * @module api/PostsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new PostsApi. 
   * @alias module:api/PostsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the diabetesTherapiesGet operation.
     * @callback module:api/PostsApi~diabetesTherapiesGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Feed} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List Posts
     * posts list 
     * @param {Number} json Scope under which the request is made; determines fields present in response.
     * @param {module:api/PostsApi~diabetesTherapiesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Feed}
     */
    this.diabetesTherapiesGet = function(json, callback) {
      var postBody = null;

      // verify the required parameter 'json' is set
      if (json == undefined || json == null) {
        throw new Error("Missing the required parameter 'json' when calling diabetesTherapiesGet");
      }


      var pathParams = {
      };
      var queryParams = {
        'json': json
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Feed;

      return this.apiClient.callApi(
        '/diabetes-therapies', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
